<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SWOTify Sentiment Analysis</title>
    <link rel="icon" href="assets/sentiment-analysis.png">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.0/css/bulma.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.0/css/versions/bulma-no-dark-mode.min.css">
    <link rel="stylesheet" href="https://bulma.io/vendor/fontawesome-free-6.5.2-web/css/all.min.css">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.13.3/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="dashboard/dashboard.css">
</head>

<body>
    <section class="hero is-small is-primary">
        <div class="hero-body">
            <p class="subtitle">SWOTify Sentiment Analysis</p>
        </div>
    </section>
    <section class="section p-2">
        <div class="container is-fluid">
            <div class="columns">
                <div class="column is-3">
                    <div class="box">
                        <p class="title is-5">CSG Officers List</p>
                        <div class="field">
                            <label class="label">Full Name</label>
                            <div class="control has-icons-left has-icons-right">
                                <input class="input" type="text" id="csg-officers" placeholder="Enter name">
                                <span class="icon is-small is-left">
                                    <i class="fas fa-user"></i>
                                </span>
                            </div>
                            <!-- <p class="help is-success">This username is available</p> -->
                        </div>

                        <div class="field">
                            <p class="control">
                                <button id="sa_evaluate" class="button is-primary is-fullwidth">
                                    View Result
                                </button>
                            </p>
                        </div>

                    </div>
                </div>


                <div class="column">
                    <div class="columns">
                        <div class="column">
                            <div class="box">
                                <p class="subtitle">
                                    Total Evaluations Received
                                </p>
                                <p id="total_eval_received" class="main_score title is-4">123</p>
                            </div>
                        </div>

                        <div class="column">
                            <div class="box">
                                <p class="subtitle">
                                    Positive Reviews
                                </p>
                                <p id="positive_sentiment" class="main_score title is-4">123</p>
                            </div>
                        </div>
                        <div class="column">
                            <div class="box">
                                <p class="subtitle">
                                    Neutral Reviews
                                </p>
                                <p id="neutral_sentiment" class="main_score title is-4">123</p>
                            </div>
                        </div>
                        <div class="column">
                            <div class="box">
                                <p class="subtitle">
                                    Negative Reviews
                                </p>
                                <p id="negative_sentiment" class="main_score title is-4">123</p>
                            </div>
                        </div>
                    </div>

                    <div class="columns">
                        <div class="column is-one-quarter">
                            <div class="box">
                                <p class="title is-5">Sentiment Distribution</p>
                                <p class="subtitle is-7">
                                    Generated by the ML Model
                                </p>

                                <canvas id="sentiment_distribution"></canvas>
                            </div>
                        </div>
                        <div class="column">
                            <div class="box">
                                <p class="title is-5">Performance Ratings</p>
                                <p class="subtitle is-7">
                                    Averaged Performance Ratings
                                </p>
                                <canvas id="performance_ratings"></canvas>
                            </div>
                        </div>
                    </div>
                    <div class="columns">
                        <div class="column">
                            <div class="box">
                                <p class="title is-5">Performance Ratings</p>
                                <p class="subtitle is-7">
                                    Averaged Performance Ratings
                                </p>

                                <!-- <canvas id="performance_ratings"></canvas> -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>


        </div>
    </section>

    <script src="https://code.jquery.com/jquery-3.7.1.js"></script>
    <script src="https://code.jquery.com/ui/1.13.3/jquery-ui.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@latest/dist/chartjs-plugin-datalabels.min.js"></script>
    <script src="dashboard/dashboard.js"></script>

</body>

</html>